name: Reusable Module Workflow
env:
  PROJECT_ID: mhalo
on:
  workflow_call:
    inputs:
      SERVICE_MODULE_NAME:
        required: true
        type: string
      SERVICE_IMAGE_NAME:
        required: true
        type: string
jobs:
  build-and-test-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
      - name: Build and run tests
        run: mvn test -pl {{ inputs.SERVICE_MODULE_NAME }} -am

  sonar-analyze:
    runs-on: ubuntu-latest
    needs:
      - build-and-test-artifact
    steps:
      - name: Analyze code
        run: echo "Analyzing code quality"
  veracode-analyze:
    needs:
      - sonar-analyze
    runs-on: ubuntu-latest
    steps:
      - name: Scan project
        run: echo "Scanning project for Veracode..."
      - name: Find vulnerabilities
        run: echo "Checking for vulnerabilities..."
  build-and-publish-image:
    runs-on: ubuntu-latest
    needs:
      - veracode-analyze
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: mvn install -pl {{ inputs.SERVICE_MODULE_NAME }} -am -DskipTests
      - name: Get commit hash
        id: get-commit-hash
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$short_sha" >> $GITHUB_OUTPUT
      - name: Tag image
        run: docker tag {{ env.PROJECT_ID }}/{{ inputs.SERVICE_IMAGE_NAME }}:1.0-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/{{ inputs.SERVICE_IMAGE_NAME }}:${{ steps.get-commit-hash.outputs.SHORT_SHA }}
      - name: Publish image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/{{ inputs.SERVICE_IMAGE_NAME }}:${{ steps.get-commit-hash.outputs.SHORT_SHA }}
